<a href="https://colab.research.google.com/github/h0806449f/YOLO_related/blob/main/Testmodel8_YOLO_v8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
HOME = os.getcwd()
print(HOME)

/content


In [3]:
# Pip install method (recommended)

!pip install ultralytics==8.0.20

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

Ultralytics YOLOv8.0.20 🚀 Python-3.10.11 torch-2.0.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 23.4/78.2 GB disk)


In [4]:
from ultralytics import YOLO
from IPython.display import display, Image

# P
YOLO 相關參數
1. task : `detect`, `classify`, `segment`
2. mode : `train`, `predict`, `val`
3. model : `YOLOv8n`.pt < `YOLOv8s`.pt < `YOLOv8m`.pt <  `YOLOv8l`.pt < `YOLOv8x`.pt 
4. conf : 預測分數
5. source : 額外資料庫來源

In [5]:
model = YOLO(f'{HOME}/yolov8n.pt')
results = model.predict(source='https://media.roboflow.com/notebooks/examples/dog.jpeg', conf=0.25)

100%|██████████| 6.23M/6.23M [00:00<00:00, 284MB/s]

Ultralytics YOLOv8.0.20 🚀 Python-3.10.11 torch-2.0.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
100%|██████████| 104k/104k [00:00<00:00, 50.2MB/s]


In [6]:
results[0].boxes.xyxy

tensor([[   0.,  314.,  625., 1278.],
        [  55.,  250.,  648., 1266.],
        [ 633.,  720.,  701.,  786.]], device='cuda:0')

In [7]:
results[0].boxes.conf

tensor([0.72713, 0.29066, 0.28456], device='cuda:0')

In [8]:
results[0].boxes.cls

tensor([ 0., 16.,  2.], device='cuda:0')

In [10]:
print(results)

[Ultralytics YOLO <class 'ultralytics.yolo.engine.results.Boxes'> masks
type: <class 'torch.Tensor'>
shape: torch.Size([3, 6])
dtype: torch.float32
 + tensor([[0.00000e+00, 3.14000e+02, 6.25000e+02, 1.27800e+03, 7.27125e-01, 0.00000e+00],
        [5.50000e+01, 2.50000e+02, 6.48000e+02, 1.26600e+03, 2.90664e-01, 1.60000e+01],
        [6.33000e+02, 7.20000e+02, 7.01000e+02, 7.86000e+02, 2.84555e-01, 2.00000e+00]], device='cuda:0')]
